title: Hello World # your site title
subtitle: Blog podróżniczy by 16
author: Stanisław Kowański
email: helloworld@f4dev.me # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Hobbystyczny blog podróżniczy, od czasu do czasu, pisany przez
  nastolatka wyjeżdżającego z rodzicami ;).
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://hw.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username: janczizikow # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
social:
  name: Stanisław Kowański
  links:
    - http://f4dev.me
    - http://facebook.com/kajmaken

disqus:
  #shortname:  # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
