backend:
  name: git-gateway
media_folder: "assets/img/uploads"
publish_mode: editorial_workflow
collections:
  - name: "days"
    label: "Dni"
    label_singular: "Dzień"
    folder: "_posts/days"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "day"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Obrazek wyróżniający", name: "thumbnail", widget: "image", required: false}
      - label: "Miasto"
        name: "city"
        widget: "relation"
        collection: "cities"
        searchFields: ["title"]
        valueField: "title"
      - {label: "Treść", name: "body", widget: "markdown"}
  - name: "cities"
    label: "Miasta"
    label_singular: "Miasto"
    folder: "_posts/cities"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "city"}
      - {label: "Nazwa", name: "title", widget: "string"}
      - label: "Kontynent"
        name: "continent"
        widget: "select"
        options:
          - {label: "Europa", value: "europe"}
          - {label: "Azja", value: "asia"}
          - {label: "Afryka", value: "africa"}
          - {label: "Ameryka Południowa", value: "southam"}
          - {label: "Ameryka Północna", value: "northam"}
          - {label: "Antarktyda", value: "antarctica"}
          - {label: "Australia", value: "australia"}
      - {label: "Kraj", name: "country", widget: "string"}
      - {label: "Obrazek wyróżniający", name: "thumbnail", widget: "image", required: false}
