backend:
  name: git-gateway
media_folder: "assets/img/uploads"
publish_mode: editorial_workflow
collections:
  - name: "days"
    label: "Dni"
    label_singular: "Dzień"
    folder: "_posts/days"
    create: true
    slug: "day-{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Obrazek wyróżniający", name: "featured-img", widget: "image", required: false}
      - label: "Kraj"
        name: "country"
        widget: "relation"
        collection: "countries"
        searchFields: ["title", "code"]
        valueField: "title"
      - {label: "Tagi", name: "tags", widget: "list"}
      - {label: "Treść", name: "body", widget: "markdown"}
  - name: "countries"
    label: "Kraje"
    label_singular: "Kraj"
    folder: "_posts/countries"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "country"}
      - {label: "Nazwa", name: "title", widget: "string"}
      - {label: "Kod kraju", name: "code", widget: "string"}
      - label: "Kontynent"
        name: "continent"
        widget: "select"
        options:
          - {label: "Europa", value: "europe"}
          - {label: "Azja", value: "asia"}
          - {label: "Afryka", value: "africa"}
          - {label: "Ameryka Południowa", value: "southam"}
          - {label: "Ameryka Północna", value: "northam"}
          - {label: "Antarktyda", value: "antarctica"}
          - {label: "Australia", value: "australia"}
      - {label: "Obrazek wyróżniający", name: "featured-img", widget: "image", required: false}
  - name: "posts"
    label: "Posty"
    label_singular: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Obrazek wyróżniający", name: "featured-img", widget: "image", required: false}
      - {label: "Tagi", name: "tags", widget: "list"}
      - {label: "Treść", name: "body", widget: "markdown"}
